# Generated by Django 4.0.4 on 2022-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('data', models.DateField(help_text='Formato da Data : YYYY/MM/DD')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='static\\posts\\images')),
            ],
        ),
    ]
