# Generated by Django 4.0.4 on 2022-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_post_header_image_cadeira_ano_letivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='docente_teorica',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='docentes_praticas',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='linguagens',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='professor',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
    ]
