# Generated by Django 4.0.4 on 2022-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_cadeira_docente_teorica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='interesses/')),
            ],
        ),
    ]
