# Generated by Django 4.0.4 on 2022-05-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=2020)),
                ('imagem', models.ImageField(upload_to='certificados/')),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
                ('ano_inicio', models.IntegerField(default=1)),
                ('ano_fim', models.IntegerField(default=1)),
                ('imagem', models.ImageField(upload_to='escolas/')),
            ],
        ),
    ]
