# Generated by Django 4.0.4 on 2022-05-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificados_competencias_escola'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificados',
            new_name='Certificado',
        ),
        migrations.RenameModel(
            old_name='Competencias',
            new_name='Competencia',
        ),
    ]
