# Generated by Django 4.0.4 on 2022-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_certificado_imagem_certificado_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='link',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
