# Generated by Django 4.0.4 on 2022-05-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_certificado_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='tiulo',
            new_name='titulo',
        ),
    ]
