# Generated by Django 4.0.4 on 2022-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_tiulo_projeto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.IntegerField(default=2020),
        ),
    ]
