# Generated by Django 4.0.4 on 2022-06-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_laboratorio_noticia_site_tecnologia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Linguagem',
        ),
        migrations.AddField(
            model_name='projeto',
            name='final',
            field=models.IntegerField(default=1),
        ),
    ]
